spring:
  #shell:
    #interactive:
      #enabled: false
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql