spring:
  #shell:
    #interactive:
      #enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/maindb
      # host: localhost
      # port: 27017
      # database: maindb
    sql:
      init:
        mode: never
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: false
    h2:
      console:
        enabled: false